### ISSUE TITLE
Short font declaration issue (Font Awesome)

### ISSUE THREAD

**Issue by Grawl** [jonathantneal/postcss-font-weights#4]
[Font Awesome](//fontawesome.io) is declaring their fonts like this:

```
font: normal normal normal 14px/1 FontAwesome;
```

and after `postcss-font-weights` this string becomes this:

```
font: 400 400 400 14px/1 FontAwesome
```

and it's not working anymore.

Because in Font Awesome, it's this:

```css
.fa {
  /* style | variant | weight | size/line-height | family */
  font: normal normal normal 14px/1 FontAwesome;
  …
}
```

> [font - CSS | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font)

So, this is equal to this:

```css
.fa {
  font-style: normal;
  font-variant: normal;
  weight: normal;
  font-size: 14px;
  line-height: 1;
  font-family: FontAwesome;
  …
}
```

And a string generated by `postcss-font-weights` is equal to this:

```css
.fa {
  font-style: 400; /* Invalid property value */
  font-variant: 400; /* Invalid property value */
  weight: 400;
  font-size: 14px;
  line-height: 1;
  font-family: FontAwesome;
  …
}
```

But because of shorten syntax of Font Awesome, `font-family` property is broken too, and I see a rectangles instead of Font Awesome glyphs.

**So, my proposal is to disable `postcss-font-weights` for shorten `font` declaration**, or, at least, disable for `normal` values in shorten `font` declaration.
